theme: jekyll-theme-minimal
title: Vivian Kowieski Personal Page
description: A basic guide to get to know me
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Syntax
    url: syntax
  - title: Example
    url: example
  - title: Flightless Birds
    url: test
  - title: Resume
    url: assets/files/sample_resume.pdf

